{% set setup_data = load_setup_py_data() %}

package:
  name: cml_pipelines
  version: {{ setup_data['version'] }}


source:
  git_url: ../
  # git_rev: {{ 'v' + setup_data['version'] }}  # always use tagged version

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  number: {{ environ.get("PKG_BUILDNUM", 0) }}

  # Specify additional env vars pass through
  # script_env:
  #   - ENV_VAR_HERE

requirements:
  build:
    - python {{ python }}
    - setuptools
    - dask
    - distributed

  run:
    - python {{ python }}
    - dask
    - distributed

test:
  # Test that we can import the package
  imports:
    - cml_pipelines
    - cml_pipelines.hooks

about:
  home: https://github.com/pennmem/cml_pipelines
  summary: {{ setup_data['description'] }}
  # license: FIXME
  # license_file: FIXME
